; credentials.ini
[auth]
build_flags =
    -D WIFI_SSID=\"<Wifi SSID>\"
    -D WIFI_PASS=\"<Wifi Password>\"
    -D DISPLAY_URL=\"http://your-display-service/api/data\"
    -D DEVICE_ID=\"co2-monitor-01\"
