; credentials.ini
[auth]
build_flags =
    -D WIFI_SSID=\"<Wifi SSID>\"
    -D WIFI_PASS=\"<Wifi Password>\"
    -D GAS_URL=\"<GAS Web App URL>\"
    -D DISPLAY_URL=\"http://your-display-service/api/data\"
    -D DEVICE_ID=\"co2-monitor-01\"
    -D ENABLE_GAS=0
    -D ENABLE_HTTP_SERVER=0
